# Configuración para Render (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.packages-to-scan=com.ecommerce.pedidos_pagos.infrastructure.adapter.out.persistence.entity
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}

# Logging
logging.level.root=INFO
logging.level.com.ecommerce=DEBUG


